#!/bin/bash
#####################################################################
# Program: 
# Description:
#
# Author: Wesley Rodrigues da Silva <wesley.it@gmail.com>
#####################################################################

## Define the working directory and a timestamp
WORK_DIR="$(dirname $0)"
TIMESTAMP="$(date +'%Y%m%d_%H-%M-%S')"


